### ISSUE TITLE
fibc benchmark fails with C level assertion

### ISSUE THREAD

**Issue by ktakashi** [picrin-scheme/picrin#203]
One of the R6RS benchmark (converted for R7RS by Atsushi Saito) fails with C assertion.

```scheme
(import (scheme base))

(define (succ n) (+ n 1))
(define (pred n) (- n 1))

;;; fib with peano arithmetic (using numbers) with call/cc

(define (addc x y k)
  (if (zero? y)
    (k x)
    (addc (succ x) (pred y) k)))

(define (fibc x c)
  (if (zero? x)
    (c 0)
    (if (zero? (pred x))
      (c 1)
      (addc (call-with-current-continuation
             (lambda (c) (fibc (pred x) c)))
            (call-with-current-continuation
             (lambda (c) (fibc (pred (pred x)) c)))
            c))))
(fibc 10 30)
```
The result;
```
assertion "false" failed: file "/home/t.kato/work/picrin/include/picrin/value.h", line 278, function: pic_type_repr
```

Environment:
Cygwin 32 bit on Windows 7.

**Comment by omasanori** [comment]
At ad6833ac79c656c9e4cec0723cc647b9f6b10a48 on Gentoo Linux amd64, I got an another error ([the error log](https://gist.github.com/omasanori/e273b68efc0ae46e6840) with @KeenS' code) but it seems correct, since `c`, or `k`, used as a procedure but actually it is a number.

The expression `(fibc 10 (lambda (n) n))` evaluated without any error and the result is `55`.

**Comment by wasabiz** [comment]
@omasanori is right. Apparently this is not Picrin's fault (probably it *used to be* Picrin's but now it's not).

I am closing this issue. Still, feel free to post a report bug in case you found. Thanks.
