### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by leon-vv** [picrin-scheme/picrin#259]
Why is the MIT license used instead of a GPL license?

**Comment by KeenS** [comment]
Rather why do you want it to be GPL licensed?

**Comment by leon-vv** [comment]
Because I think copylefted software does a better job at keeping the software free in the future. What do you think about it?

Related blog article: http://ebb.org/bkuhn/blog/2014/01/26/llvm.html

**Comment by KeenS** [comment]
@leon-vv 
I understand your opinion. That's one aspect of GPL.
However, being free is not the ultimate goal of picrin. Picrin is embeddable and hackable. Freeing programmers from worrying about licensing is important.

If you want to know more detailed policy of picirn, ask @wasabiz .

**Comment by wasabiz** [comment]
@leon-vv 

Sorry for the late response. I leave my comment on this topic to close the issue.

Because Picrin is intended to work as an embedded application. In fact I am using picrin on our own CPU  for which my group designed the ISA, micro architecture, simulator, and C compiler. In the world of embedded software, "just work" is the most important goal and at the same time is the most difficult goal to achieve. It is usual that developing an buggy OS goes with an buggy debugger and buggy compiler and buggy simulator, without any reviews, and product is finally released with many bugs. In such an environment Picrin's small footprint and detachability of libc and libm are very useful and helpful for debugging. You can build reliable system with GC on top of your own bare-metal cpu only with some small modifications. However, it is often that the modifications include a great deal of system-specific information which is difficult to be published. Involving hardware makes it very difficult unlike the way only software is involved, sometimes for political reasons or sometimes time and money. Anyway, GPL does not fit to the model of embedded application model (I think the only surviving software licensed under GPL is gcc toolchain...).
