### ISSUE TITLE
Where to put libraries?

### ISSUE THREAD

**Issue by Taknamay** [picrin-scheme/picrin#260]
Hello, I am trying to write my own libraries but I am not sure where to put them. For example, in Chibi scheme I put them in /usr/local/share/chibi/a/b.scm and I can import them with (import (a b)).

Is there a similar location for picrin? Also, can I locally load libraries somehow?

**Comment by wasabiz** [comment]
Hi, @Taknamay. Thank you for trying to use Picrin.

Picrin doesn't look up for any library path at import time. If you want to make your own library visible from import statement, 'load' procedure would be useful to you. The reason picrin doesn't have library path is that we wanted to avoid ambiguity of import. In case your own library `(a b)` unintentionally conflicts with picrin's system library `(a b)` you would need to choose which to use by adding an annotation to import but R7RS import syntax lacks such a system. We thought following to the standard was more important than providing useful syntax extension and that's why the import is what it is now. FYI, picrin's import semantics is very similar to that of common lisp. Please check it out.

```scheme
(load "a/b.scm")

(import (a b))
```

> Also, can I locally load libraries somehow?

Picrin doesn't support local libraries for now but can you tell us your assuming scenario in more detail? I'd like to add it if it's really worth it.

**Comment by Taknamay** [comment]
Thank you, that is a really helpful explanation. Closing this issue.

The locally loaded libraries was not for a specific scenario; I am experimenting with implementations and was curious about whether I could find a workaround for SRFIs I want by using SRFI libraries written in Scheme (for exactly this kind of use - where the implementation does not provide a particular SRFI). That was actually the motivation for this question in the first place.

**Comment by wasabiz** [comment]
I see. I think naming `(my srfi XX)` or something is maybe an easy way. It should work on every r7rs implementation.

Anyway good luck with your experiments! If you found bugs on picrin, please open issues here.
