### ISSUE TITLE
simple example doesn't work

### ISSUE THREAD

**Issue by JeNeSuisPasDave** [picrin-scheme/picrin#307]
This simple example from [Teach Yourself Scheme in Fixnum Days](http://ds26gte.github.io/tyscheme/index-Z-H-3.html#node_chap_1) does not work.

If I put the code in a "hello.scm" file and run `picrin hello.scm` I get this:

```
$ picrin hello.scm
error: "uninitialized global variable: 2.16356e-314" 2.16356e-314
  at (anonymous lambda) (unknown location)
  at (anonymous lambda) (native function)
```

If I type the code into the REPL, I get this:

```
$ picrin
> (begin
  (display "Hello, World!")
  (newline))
Hello, World!
#undefined
> 
```

Yep, I'm trying to learn Scheme. Perhaps picrin isn't the best tool for that ...

**Comment by KeenS** [comment]
@JeNeSuisPasDave 
That's because picrin is R7RS implementation. Unlike R5RS, R7RS scheme separates functions into libraries and you need to explicitly import them. To run your example, put `import` like below,

```scheme
(import (scheme base)
        (scheme write))

(begin
 (display "Hello, World!")
 (newline))
```

`(scheme base)` is the basis library and `(scheme write)` is a IO library. This is R7RS way.
However, if you want to learn R5RS scheme, you can use `(scheme r5rs)` library, which is compat library to R5RS scheme,

```scheme
(import (scheme r5rs))

(begin
 (display "Hello, World!")
 (newline))
```

Bests

**Comment by JeNeSuisPasDave** [comment]
Forgot to say "thanks". :-/
